version: 2.1

jobs:
  build:
    docker:
      - image: "gcc:7.4"
    steps:
      - checkout
      - run:
          name: Install SUDO
          command: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install CMAKE
          command: apt-get update && sudo apt-get install -y cmake
      - run:
          name: Update Submodules
          command: git submodule update --init --recursive
      - run:
          name: Build Poker Hand Clustering
          command: make
      - run:
          name: Build And Execute Unit Testing
          command: make check
